# Generated by Django 6.0.4 on 2026-04-28 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🏆', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('cgpa', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('tab_label', models.CharField(blank=True, help_text="Short label for the tab e.g. 'Asst. System Engineer'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Page Visit',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sankar K', max_length=100)),
                ('title', models.CharField(default='Backend Dev.', max_length=100)),
                ('tagline', models.CharField(default='Available for Backend Roles', max_length=200)),
                ('tech_stack', models.CharField(default='Python · Django · DRF · PostgreSQL · Redis · Celery · OAuth · JWT', max_length=300)),
                ('bio', models.TextField(default='I build backend systems that scale.')),
                ('location', models.CharField(default='Chennai, Tamil Nadu, India', max_length=100)),
                ('email', models.EmailField(default='kaliyannansankar1999@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91-8754844723', max_length=20)),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/sankar-django-dev')),
                ('github_url', models.URLField(default='https://github.com/Sankar26-py')),
                ('github_project_url', models.URLField(default='https://github.com/Sankar26-py/foodOnline')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_open_to_work', models.BooleanField(default=True)),
                ('footer_text', models.CharField(default='Designed & built — Sankar K © 2026 · Python Django Developer · Chennai, India', max_length=300)),
                ('years_exp', models.CharField(default='3.6+', max_length=10)),
                ('perf_gain', models.CharField(default='30%', max_length=10)),
                ('automation_gain', models.CharField(default='40%', max_length=10)),
                ('api_count', models.CharField(default='5+', max_length=10)),
                ('cgpa', models.CharField(default='9.54', max_length=10)),
                ('about_para1', models.TextField(default='Results-driven Python Backend Developer with 3.6+ years at Tata Consultancy Services, progressing from Graduate Trainee all the way to System Engineer through consistent technical delivery.')),
                ('about_para2', models.TextField(default='I specialise in building scalable Django REST APIs, implementing OAuth 2.0 and JWT authentication, Redis caching strategies, and designing Celery-powered async pipelines.')),
                ('about_para3', models.TextField(default='Currently preparing for the Microsoft Azure Developer Associate (AZ-204) certification to deepen cloud-integrated backend capabilities.')),
                ('in_progress_title', models.CharField(blank=True, default='☁ AZ-204 — Azure Developer Associate', max_length=200)),
                ('in_progress_text', models.TextField(blank=True, default='Preparing to build cloud-integrated backend solutions on Microsoft Azure.')),
                ('company_name', models.CharField(default='Tata Consultancy Services', max_length=100)),
                ('company_sub', models.CharField(default='Chennai, Tamil Nadu · Remote · Full-time', max_length=150)),
                ('company_duration', models.CharField(default='Sep 2022 – Present · 3 yrs 8 mos', max_length=100)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_external', models.BooleanField(default=True)),
                ('tags', models.CharField(help_text='Comma-separated: Django, DRF, PostgreSQL', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='portfolio_app.experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='portfolio_app.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🐍', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='portfolio_app.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_highlights', to='portfolio_app.profile')),
            ],
            options={
                'verbose_name': 'About Highlight',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio_app.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
